### ISSUE TITLE
Doesn't build on nightly 1.28

### ISSUE THREAD

**Issue by tov** [CensoredUsername/dynasm-rs#32]
Using rustc 1.28.0-nightly (a3085756e 2018-05-19), I get the following when I try to build dynasm:

```
error[E0063]: missing field `edition` in initializer of `syntax::ext::base::SyntaxExtension`
  --> /Users/tov/.cargo/registry/src/github.com-1ecc6299db9ec823/dynasm-0.2.0/src/lib.rs:44:35
   |
44 |                                   SyntaxExtension::NormalTT {
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^ missing `edition`
```

This is the same for dynasm 0.1.4 and 0.2.0.

**Comment by tov** [comment]
Here's a PR: #33 

I'm not sure if this is the right solution in terms of how you want to handle the transition to the upcoming 2008 edition, but this works for now.

**Comment by CensoredUsername** [comment]
I've published dynasm 0.2.1 which should have the problem fixed.

**Comment by tov** [comment]
Awesome. Thanks!
